language: php
php:
  - 5.4
  - 5.5

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install

script:
  - php vendor/bin/phpunit src
  - php vendor/bin/phpspec run
  - php vendor/bin/behat --config behat.yml

after_script:
  - php vendor/bin/coveralls -v

